name: args_macro
description: Generates a parser for command-line arguments based on your data class.
repository: https://github.com/alexeyinkin/dart-args-macro.git
version: 0.1.0-8.dev

environment:
  sdk: ^3.5.0-164

topics:
  - cli
  - macros

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  common_macros: ^0.1.0-4.dev
  macro_util: ^0.1.0-9.dev
  macros: ^0.1.0-main.5

dev_dependencies:
  matching: ^0.1.3
  show_augmentation: ^0.1.0-7.dev
  test: ^1.25.5
  test_util: ^0.1.1
  total_lints: ^3.4.0

dependency_overrides:
  #common_macros: { path: ../dart-common-macros }
  #lsp_client: { path: ../dart-lsp-client }
  #macro_util: { path: ../dart-macro-util }
  #matching: { path: ../dart-matching }
  #show_augmentation: { path: ../dart-show-augmentation }
